Collecting package metadata: ...working... done
Solving environment: ...working... 
The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:

  - defaults/linux-64::bokeh==0.12.13=py36h2f9c1c0_0
  - defaults/linux-64::scikit-image==0.13.1=py36h14c3975_1
  - defaults/linux-64::scikit-learn==0.19.1=py36h7aa7ec6_0
  - defaults/linux-64::dask==0.16.1=py36_0
  - defaults/linux-64::tensorflow-base==1.9.0=mkl_py36h2ca6a6a_0
  - defaults/linux-64::seaborn==0.8.1=py36hfad7ec4_0
  - defaults/linux-64::tensorboard==1.9.0=py36hf484d3e_0
  - defaults/linux-64::datashape==0.5.4=py36h3ad6b5c_0
  - defaults/linux-64::mkl_fft==1.0.4=py36h4414c95_1
  - defaults/linux-64::numexpr==2.6.4=py36hc4a3f9a_0
  - defaults/linux-64::patsy==0.5.0=py36_0
  - defaults/linux-64::astropy==2.0.3=py36h14c3975_0
  - defaults/linux-64::bkcharts==0.2=py36h735825a_0
  - defaults/linux-64::statsmodels==0.8.0=py36h8533d0b_0
  - defaults/linux-64::numba==0.36.2=np114py36hc6662d5_0
  - defaults/linux-64::scipy==1.0.0=py36hbf646e7_0
  - defaults/linux-64::mkl_random==1.0.1=py36h4414c95_1
  - defaults/linux-64::pytables==3.4.4=py36ha205bf6_0
  - defaults/linux-64::blaze==0.11.3=py36h4e06776_0
  - defaults/linux-64::bottleneck==1.2.1=py36haac1ea0_0
  - defaults/linux-64::h5py==2.8.0=py36h8d01980_0
  - defaults/linux-64::imageio==2.2.0=py36he555465_0
  - pytorch/linux-64::pytorch==1.1.0=py3.6_cuda10.0.130_cudnn7.5.1_0
  - defaults/linux-64::pywavelets==0.5.2=py36he602eb0_0
  - defaults/linux-64::matplotlib==2.1.2=py36h0e671d2_0
  - defaults/linux-64::hdijupyterutils==0.12.5=py36_0
  - defaults/linux-64::odo==0.5.1=py36h90ed295_0
  - defaults/linux-64::autovizwidget==0.12.5=py36_0
  - defaults/linux-64::pandas==0.22.0=py36hf484d3e_0
failed
